### PR TITLE
Change swap uri constant from http to https

### PR DESCRIPTION
**Pull request by Garllon**
The https://swapi.co/ we can't reach anymore without https, so i switched the API_URI constant.

### CODE REVIEW

**Comment by philnash** [comment]
Thanks for this! Just updating the project so that the tests run again.

**Comment by philnash** [comment]
Ok, tests are passing on master. Would you mind rebasing the latest from master and trying this again?

**Comment by Garllon** [comment]
Done, i skipped the version change. It is your decision what is the right one. I prefer version 2, because we increased the minimum ruby version.

**Comment by philnash** [comment]
Thanks and done. Updated to version 2 🙂

**Pull request merged**
